version: 1.1.{build}
image: Visual Studio 2017

clone_folder: c:\azure-functions-cli

environment:
  CLI_DEBUG: 1

build_script:
- cmd: build.cmd

test: off

artifacts:
- path: deploy\Azure.Functions.*.zip
  name: Release
- path: deployx86\Azure.Functions.*.zip
  name: Release
- path: deployx64\Azure.Functions.*.zip
  name: Release
- path: dist\test\*.html
  name: Test
